// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/JairoRiver/time_keeper/internal/view/layout"

func Landing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col min-h-screen bg-gray-50\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = layout.Header(false, false).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main class=\"flex-1 flex flex-col items-center justify-center px-6 py-16 text-center\"><span class=\"text-6xl mb-6\">⏰</span><h1 class=\"text-4xl font-bold text-gray-800 mb-4\">Registra tu tiempo, <br>sin complicaciones</h1><p class=\"text-lg text-gray-500 max-w-md mb-10\">TimeKeeper es una herramienta simple para registrar en qué inviertes tu tiempo cada día. Sin registro obligatorio — empieza ahora mismo.</p><div class=\"flex flex-col sm:flex-row gap-4 justify-center\"><a href=\"/try\" class=\"px-8 py-3 rounded-full bg-green-400 text-white font-semibold text-lg hover:bg-green-500 transition-colors\">Probar sin cuenta</a> <a href=\"/auth/login\" class=\"px-8 py-3 rounded-full border-2 border-blue-400 text-blue-600 font-semibold text-lg hover:bg-blue-50 transition-colors\">Entrar</a></div><div class=\"mt-16 grid grid-cols-3 gap-8 max-w-2xl text-left\"><div class=\"bg-white rounded-xl p-5 shadow-sm\"><div class=\"text-2xl mb-2\">🏷️</div><h3 class=\"font-semibold text-gray-700 mb-1\">Etiquetas</h3><p class=\"text-sm text-gray-400\">Organiza tus entradas con tags personalizados.</p></div><div class=\"bg-white rounded-xl p-5 shadow-sm\"><div class=\"text-2xl mb-2\">📅</div><h3 class=\"font-semibold text-gray-700 mb-1\">Historial</h3><p class=\"text-sm text-gray-400\">Consulta tus registros agrupados por día.</p></div><div class=\"bg-white rounded-xl p-5 shadow-sm\"><div class=\"text-2xl mb-2\">📊</div><h3 class=\"font-semibold text-gray-700 mb-1\">Resumen</h3><p class=\"text-sm text-gray-400\">Visualiza tu semana en un calendario de bloques.</p></div></div></main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("TimeKeeper").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
