database:
  db_source: ${DB_SOURCE:-postgresql://root:secret@localhost:5432/time_keeper?sslmode=disable}
  db_name: time_keeper
server:
  address: 0.0.0.0:8080
  secure_cookies: ${SECURE_COOKIES:-false}
  enable_swagger: ${ENABLE_SWAGGER:-true}
