// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TimeEntry struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Tag       string           `json:"tag"`
	TimeStart pgtype.Timestamp `json:"time_start"`
	TimeEnd   pgtype.Timestamp `json:"time_end"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID        `json:"id"`
	Email          pgtype.Text      `json:"email"`
	Role           string           `json:"role"`
	EmailValidated bool             `json:"email_validated"`
	IsActive       bool             `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
