// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TimeEntry struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Tag       string             `json:"tag"`
	TimeStart pgtype.Timestamptz `json:"time_start"`
	TimeEnd   pgtype.Timestamptz `json:"time_end"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          pgtype.Text        `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	Role           string             `json:"role"`
	EmailValidated bool               `json:"email_validated"`
	IsActive       bool               `json:"is_active"`
	SecretTokenKey string             `json:"secret_token_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
